[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "google-genai>=1.25.0",
    "psutil>=7.0.0",
    "replit>=4.1.2",
    "sift-stack-py>=0.7.0",
]
